OOP first review
alex-markin/mesto-project pull request #2
Opened 2023-02-24 08:56 UTC by alex-markin

2023-02-24 13:49 UTC, antonmishchenkov requested changes
Хорошая работа, так держать! Код аккуратен и читабелен.
Есть ряд замечаний, которые необходимо исправить, чтобы работу можно было принять. Все они отмечены как "Надо исправить".

Также будет здорово, если проработаете поинты "Можно лучше".

Успехов на второй итерации!

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/api.js
> +      console.log(`Ошибка ${err}`);
**Надо исправить:**

Ошибка `err` будет не определена в случае возникновения. Для корректного отображения следует передавать ее в `catch` в качестве аргумента:

`catch (err) {...}`

Следует исправить здесь и **везде далее** во всех запросах на сервер во всех файлах проекта

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/FormValidator.js
> +    const inputList = Array.from(
**Надо исправить:**

Список полей формы и кнопку сабмита необходимо вынести в конструктор класса в качестве полей, чтобы не искать элементы внутри метода и не передавать их в другие методы. 

Необходимо для того, чтобы доступ к этим статичным элементам формы был во всем классе в любой момент времени

```
this._inputList = ...
this._submitButton = ... 
```

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/FormValidator.js
> +// function enableValidation(config) {
**Надо исправить:**

Неинформативные комментарии и бэкап код следует удалять перед отправкой проекта на проверку

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/globalConsts.js
> +export const userID = "535b40ada043188a626ed8d6"; // уникальный ID пользователя
**Надо исправить:**

ID пользователя должен каждый раз браться с сервера, поэтому данную константу следует удалить.

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/Card.js
> +    if (this._item.owner._id == this._profile._id) {
**Надо исправить:**

Следует использовать строгое равенство, чтобы избежать ошибок приведения типов

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/Card.js
> +    if (this._item.likes.some((like) => like._id == this._profile._id)) {
**Надо исправить:**

Следует использовать строгое равенство, чтобы избежать ошибок приведения типов

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/Popup.js
> +    if (evt.key == "Escape") {
**Надо исправить:**

Следует использовать строгое равенство

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/Popup.js
> +    document.addEventListener("keydown", this._handleEscClose.bind(this));
**Надо исправить:**

Привязку метода к контексту следует выполнить единоразово к конструкторе класса

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/Popup.js
> +      this._closePopupByOverlayClick.bind(this)
**Надо исправить:**

Привязку метода к контексту следует выполнить единоразово к конструкторе класса

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/UserInfo.js
> +  async getUserInfo() {
**Надо исправить:**

Класс UserInfo должен описывать только DOM логику информации пользователя. Метод `get` должен возвращать объект текущих значений имени, профессии и аватара, а метод `set` устанавливать соответствующие значения в эти поля.

Всю серверную логику следует описывать в исполнительно файле `index.js`.

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/UserInfo.js
> +      localStorage.setItem("name", sendProfileChanges.name);
**Надо исправить:**

Нам не за чем дополнительно сохранять данные пользователя в локальное хранилище. Данные, которые мы получаем с сервера при первичной загрузке приложения, должны записываться в поля данного класса, и в дальнейшем работа с информацией пользователя должна вестись именно через экземпляр класса UserInfo.

Мы всегда можем получить текущую информацию о пользователя с помощью `get` метода класса

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/Card.js
> +  async _handleDeleteClick() {
**Надо исправить:**

Класс Card должен описывать только DOM логику элемента карточки. Всю серверную логику следует выполнять в файле `index.js`.

То есть при создании экземпляра класса Card, мы описываем его колбэки-запросы на сервер, после успешного вызова которых (получения данных с сервера) как раз-таки следует вызывать соответствующие DOM методы класса Card.

Например, описывая колбэк-лайк карточки, сперва выполняем запрос установки лайка на сервер, а затем при успешном ответе вызываем DOM метод установки лайка.

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/Card.js
> +      this._element.remove();
**Надо исправить:**

Соответственно, DOM функционал лайка и удаления карточки следует вынести в отдельные публичные методы класса, чтобы была возможность переиспользовать их логику обособленно от сервера

2023-02-24 13:49 UTC, antonmishchenkov commented on src/pages/index.js
> +    const userInfo = new UserInfo({
**Надо исправить:**

Для работы с информацией пользователя следует создать только один экземпляр класса UserInfo в global scope файла и использовать его везде далее (в том числе внутри функции сабмита формы редактирования профиля)

2023-02-24 13:49 UTC, antonmishchenkov commented on src/pages/index.js
> +            const popupWithImage = new PopupWithImage(".popup_image");
**Надо исправить:**

Инстанцирование данного попапа и установку слушателей для него следует вынести в global scope, чтобы переменная не создавалась каждый раз при вызове данной функции, так как попапа изображения - это статичный элемент страницы в единственном экземпляре

2023-02-24 13:49 UTC, antonmishchenkov commented on src/pages/index.js
> +    const newCardRender = new Section({
**Надо исправить:**

Для работы с контейнером карточек необходимо использовать один и тот же экземпляр класса Section. Следует создать данный в global scope файла или использовать везде далее (в том числе на строке 54). Все остальные дубликаты класса следует удалить

2023-02-24 13:49 UTC, antonmishchenkov commented on src/pages/index.js
> +        const card = new Card({
**Надо исправить:**

Чтобы не дублировать код, создание карточки следует вынести в отдельную функцию

2023-02-24 13:49 UTC, antonmishchenkov commented on src/pages/index.js
> +      avatarImg.src = updateAvatar.avatar;
**Надо исправить:**

Для DOM установки аватара пользователю следует использовать метод класса UserInfo

2023-02-24 13:49 UTC, antonmishchenkov commented on src/pages/index.js
> +  inputSelector: ".popup__input-item",
**Надо исправить:**

Конфигурационный объект, использующийся для инстанцирования экземпляров FormValidator, следует вынести в отдельную переменную, чтобы не дублировать код

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/Popup.js
> +    this._popup.addEventListener(
**Можно лучше:**

Закрытие кликом по оверлею лучше устанавливать на событие `mousedown`

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/PopupWithImage.js
> +    this._popup.querySelector(".popup__img").alt = name;
**Можно лучше:**

Чтобы не дублировать поиск элемента, `this._popup.querySelector(".popup__img")` лучше вынести в отдельную переменную

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/PopupWithForm.js
> +      this._form.querySelector(".popup__save-button").textContent = "Сохранение...";
**Надо исправить:**

Так как кнопка сабмита у форм - это `input`, то менять текстовое значение нужно для атрибута `value`, а не `textContent`

2023-02-24 13:49 UTC, antonmishchenkov commented on src/components/FormValidator.js
> +    this._formElement.addEventListener("reset", () => {
Отлично!

2023-02-25 06:24 UTC, alex-markin commented on src/components/api.js
> +      console.log(`Ошибка ${err}`);
Исправлено

2023-02-25 06:30 UTC, alex-markin commented on src/components/FormValidator.js
> +    const inputList = Array.from(
Исправлено

2023-02-25 06:31 UTC, alex-markin commented on src/components/FormValidator.js
> +// function enableValidation(config) {
исправлено

2023-02-25 06:32 UTC, alex-markin commented on src/components/globalConsts.js
> +export const userID = "535b40ada043188a626ed8d6"; // уникальный ID пользователя
исправлено

2023-02-25 06:33 UTC, alex-markin commented on src/components/Card.js
> +    if (this._item.owner._id == this._profile._id) {
исправлено

2023-02-25 06:34 UTC, alex-markin commented on src/components/Card.js
> +    if (this._item.likes.some((like) => like._id == this._profile._id)) {
исправлено

2023-02-25 06:34 UTC, alex-markin commented on src/components/Popup.js
> +    if (evt.key == "Escape") {
исправлено

2023-02-25 07:09 UTC, alex-markin commented on src/components/Popup.js
> +    document.addEventListener("keydown", this._handleEscClose.bind(this));
исправлено

2023-02-25 07:10 UTC, alex-markin commented on src/components/Popup.js
> +      this._closePopupByOverlayClick.bind(this)
исправлено

2023-02-25 07:11 UTC, alex-markin commented on src/components/UserInfo.js
> +      localStorage.setItem("name", sendProfileChanges.name);
исправлено

2023-02-25 07:17 UTC, alex-markin commented on src/pages/index.js
> +    const newCardRender = new Section({
исправлено

2023-02-25 07:18 UTC, alex-markin commented on src/pages/index.js
> +            const popupWithImage = new PopupWithImage(".popup_image");
исправлено

2023-02-25 08:08 UTC, alex-markin commented on src/pages/index.js
> +    const newCardRender = new Section({
Не совсем понятно, как переиспользовать один экземпляр Section с учётом того, что у них отличается renderer. А вводные данные при рендере базовых карточке и создании новой отличаются

2023-02-25 08:31 UTC, alex-markin commented on src/pages/index.js
> +        const card = new Card({
исправлено

2023-02-25 08:46 UTC, alex-markin commented on src/components/PopupWithForm.js
> +      this._form.querySelector(".popup__save-button").textContent = "Сохранение...";
Исправлено

2023-02-25 08:48 UTC, alex-markin commented on src/components/PopupWithImage.js
> +    this._popup.querySelector(".popup__img").alt = name;
исправлено

2023-02-25 08:49 UTC, alex-markin commented on src/components/Popup.js
> +    this._popup.addEventListener(
исправлено

2023-02-25 08:53 UTC, alex-markin commented on src/pages/index.js
> +  inputSelector: ".popup__input-item",
исправлено

2023-02-26 09:04 UTC, alex-markin commented on src/components/Card.js
> +  async _handleDeleteClick() {
исправлено

2023-02-26 09:08 UTC, alex-markin commented on src/components/Card.js
> +      this._element.remove();
исправлено

2023-02-26 09:38 UTC, alex-markin commented on src/components/UserInfo.js
> +  async getUserInfo() {
Не совсем понятен комментарий, с учётом того, что в задании описано иначе:

"Содержит публичный метод getUserInfo, который возвращает объект с данными пользователя. Данные для этого метода нужно получать от методов класса Api — подумайте над тем, как внедрить метод класса Api в getUserInfo. Когда данные пользователя нужно будет подставить в форму при открытии — метод вам пригодится.
Содержит публичный метод setUserInfo, который принимает новые данные пользователя, отправляет их на сервер и добавляет их на страницу.
"

2023-02-26 09:45 UTC, alex-markin commented on src/pages/index.js
> +    const userInfo = new UserInfo({
исправлено

2023-02-26 09:46 UTC, alex-markin commented on src/pages/index.js
> +      avatarImg.src = updateAvatar.avatar;
связано с вопросом о UserInfo

2023-02-26 09:49 UTC, alex-markin commented
Внесли исправления по итогам первого ревью. Есть ряд вопросов по UserInfo, оставил комментарии как в коде, так и как ответы к комментариям ревьюера выше.

2023-02-27 16:15 UTC, antonmishchenkov requested changes
Отлично, работа стала лучше! Еще несколько замечаний, и ее можно будет принять.

2023-02-27 16:15 UTC, antonmishchenkov commented on src/pages/index.js
> +        // примечания для ревьюера: Не совсем понятно, как переиспользовать один экземпляр Section с учётом того, что у них отличается renderer. А вводные данные при рендере базовых карточек и создан
**Надо исправить:**

На абстрактном уровне сущностей контейнер карточек должен маппиться только с одним экземпляром класса Section. Это то же самое, что мы создаем один экземпляр UserInfo для работы с пользователем. Создавать каждый раз новый экземпляр UserInfo для того, чтобы что-то сделать с данными пользователя мы же не станем. Аналогично для контейнера карточек.

Мы должны таким образом описать `renderer`, чтобы он работал одинаково для начальных карточек и для карточек из формы. Иначе пропадает смысл создания данного класса. Метод `renderer` не должен знать, откуда ему приходят данные, поэтому при его объявлении мы можем сами описать нужную нам логику передачи данных и их использования.

Если в приложении появится еще один контейнер, в котором мы будем хранить другие элементы (например, список друзей пользователя), то тогда нам уже потребуется создать новый экземпляр Section с новым `renderer`

2023-02-27 16:15 UTC, antonmishchenkov commented on src/pages/index.js
> +      avatarImg.src = updateAvatar.avatar;
**Надо исправить**

При текущем подходе данная DOM логика уже прописана внутри метода `setUserInfo`, поэтому здесь необходимо использовать именно его вместо данной строи и строки выше.

Либо вынести логику установки аватара пользователю в отдельный метод класса UserInfo

2023-02-27 16:15 UTC, antonmishchenkov commented on src/components/UserInfo.js
> +  async getUserInfo() {
Да, действительно, данное требование есть в описании к ПР.
Обсужу с коллегами его актуальность и вернусь с апдейтом на следующей итерации.

2023-02-28 14:49 UTC, alex-markin commented on src/pages/index.js
> +        // примечания для ревьюера: Не совсем понятно, как переиспользовать один экземпляр Section с учётом того, что у них отличается renderer. А вводные данные при рендере базовых карточек и создан
исправлено

2023-02-28 15:04 UTC, alex-markin commented on src/pages/index.js
> +      avatarImg.src = updateAvatar.avatar;
Выделил изменение аватара в отдельную функцию, это выглядит более аккуратно.

2023-03-01 12:15 UTC, antonmishchenkov requested changes
Последнее замечание, и работу можно будет принять.

2023-03-01 12:15 UTC, antonmishchenkov commented on src/pages/index.js
> +      const newCardRender = renderCards({
**Надо исправить:**

Экземпляр Section все еще создается два раза. Здесь и на строке 124. 

Нам не нужно передавать параметр `items` при использовании контейнера для добавления карточек из формы. Параметр `items` нужен только для передачи начальных элементов, которые отрисуются в контейнере при загрузке приложения. Новые же карточки из формы следует добавлять с помощью метода `prependItem`.

Соответственно, чтобы решить текущую проблему, следует поступить таким образом:

1. Объявляем глобально переменную контейнера карточек через `let`: `let cardsContainer`
2. На строке 124 присваиваем этой переменной вызов `renderCards` или просто сразу присваиваем `new Section(...)`
3. На этой строке НЕ создаем новый экземпляр, а используем глобальный: `cardsContainer.prependItem(...)`

2023-03-01 12:15 UTC, antonmishchenkov commented on src/components/UserInfo.js
> +  async getUserInfo() {
По данному моменту все окей. Данный подход допустим к использованию. Замечание снимается

2023-03-01 15:05 UTC, alex-markin commented on src/pages/index.js
> +      const newCardRender = renderCards({
Исправлено. Хотя я не понимаю, почему в тренажере два раза используется new Section, а тут принципиально нельзя. Как по мне, код стал менее читабельным.

2023-03-02 12:43 UTC, antonmishchenkov approved these changes
Работа принимается.
Успехов в дальнейших проектах!

2023-03-03 07:56 UTC, merged